version: '3'
services:
  db:
    image: postgres:14.0-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
  api:
    image: node:lts-bullseye
    user: node
    working_dir: '/app'
    volumes:
      - './:/app'
    ports:
      - '4000:4000'
    command: 'npm run start:dev'
    depends_on:
      - db
      - pgadmin
